#-*- coding: utf-8 -*-

{
	"name": "Vit product request justifikasi",
	"version": "1.0", 
	"depends": [
		'base','account','hr','vit_product_request'
	],
	"author": "Akhmad D. Sembiring [vitraining.com]",
	"category": "Utility",
	"website": "http://vitraining.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the Vit product request justifikasi module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"security/ir.model.access.csv",
		"view/menu.xml",
		# "view/product_request.xml",
		"view/justifikasi.xml",
		# "view/employee.xml",
		# "view/coa.xml",
		# "view/user.xml",
		# "view/company.xml",
		"report/product_request.xml",
		"report/justifikasi.xml",
		"report/employee.xml",
		"report/coa.xml",
		"report/user.xml",
		"report/company.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}