#-*- coding: utf-8 -*-

{
	"name": "Vit product request justifikasi Inherited",
	"version": "1.0", 
	"depends": [
		'base','account','hr','vit_product_request'
		,'vit_product_request_justifikasi'
	],
	"author": "Akhmad D. Sembiring [vitraining.com]",
	"category": "Utility",
	"website": "http://vitraining.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the Vit product request justifikasi module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"view/justifikasi.xml",
		"view/pr.xml",
		"data/ir_sequence.xml"
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}